# Generated by Django 5.2.17 on 2026-10-03 16:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='idea',
            name='category',
            field=models.CharField(choices=[('community', 'Community'), ('technology', 'Technology'), ('environment', 'Environment'), ('education', 'Education'), ('everyday', 'Everyday life')], default='community', max_length=20),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.UUIDField()),
                ('feasibility', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('originality', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ideas.idea')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idea', 'voter_id'), name='one_rating_per_browser'), models.CheckConstraint(condition=models.Q(('feasibility__gte', 1), ('feasibility__lte', 5)), name='valid_feasibility'), models.CheckConstraint(condition=models.Q(('impact__gte', 1), ('impact__lte', 5)), name='valid_impact'), models.CheckConstraint(condition=models.Q(('originality__gte', 1), ('originality__lte', 5)), name='valid_originality')],
            },
        ),
    ]
