# Generated by Django 5.2.17 on 2026-10-03 17:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_options_idea_category_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AwardRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('award', models.CharField(default='BIC Community Choice Award', max_length=180)),
                ('submissions_open_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('voting_starts_at', models.DateTimeField()),
                ('voting_ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submissions_open_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('voting_starts_at__gt', models.F('submissions_open_at'))), name='round_submission_window'), models.CheckConstraint(condition=models.Q(('voting_ends_at__gt', models.F('voting_starts_at'))), name='round_voting_window')],
            },
        ),
        migrations.AddField(
            model_name='idea',
            name='award_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='ideas.awardround'),
        ),
        migrations.CreateModel(
            name='Ballot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('award_round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='ideas.awardround')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ballots', to='ideas.idea')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='award_ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('award_round', 'voter'), name='one_ballot_per_member_per_round')],
            },
        ),
    ]
